const { charClasses } = require('../../provisioning/data/charClasses.js')
const { charRoles } = require('../../provisioning/data/charRoles.js')
const { classTalentSpecs } = require('../../provisioning/data/classTalentSpecs.js')

const mainRosters = {
    'user@nextmail.com': [
        { 
            id: 'e76707d7-57c7-469c-933f-118a50eb17b8', 
            name: 'Thaldrion', 
            class_id: charClasses.paladin.id,
            spec_id: classTalentSpecs.paladin.protection.id,
            role_id: charRoles.tank.id,},
        {
            id: 'ccd1f7cb-d0de-4530-81fc-d48ff610658b', 
            name: 'Zarathor', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.blood.id,
            role_id: charRoles.tank.id,  
        },
        {
            id: '564bdf37-97ca-45b0-b733-97f1281ac8a9', 
            name: 'Baldur', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.protection.id,
            role_id: charRoles.tank.id, 
        },
        { 
            id: '282cfb5f-f20a-4f2b-8ad0-e89b965ef7ac', 
            name: 'Elunara', 
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.discipline.id,
            role_id: charRoles.heal.id, 
        },
        { 
            id: '53fbd70b-556a-452b-b704-38efbdb792b8', 
            name: 'Grommashar', 
            class_id: charClasses.shaman.id,
            spec_id: classTalentSpecs.shaman.restoration.id,
            role_id: charRoles.heal.id, 
        },
        { 
            id: 'acfc1c49-9a14-42f6-9e38-1599d060b98a', 
            name: 'Sylverwind', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.holy.id,
            role_id: charRoles.heal.id, 
        },
        {
            id: '8257599e-a08a-4af6-bf25-c9f6c40d6c64', 
            name: 'Danathos', 
            class_id: charClasses.paladin.id,
            spec_id: classTalentSpecs.paladin.holy.id, 
            role_id: charRoles.heal.id, 
        },
        { 
            id: 'e5065a59-3f49-4e44-97f4-fb519ce4f693', 
            name: 'Vyraeth', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.restoration.id,
            role_id: charRoles.heal.id, 
        },
        {
            id: '1645e24d-2ffe-456f-b038-9c6994fbcc0b', 
            name: 'Thalindra',
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.holy.id,
            role_id: charRoles.heal.id,
        },
        { 
            id: '6c6c031a-424a-43ae-a513-3bc36ff1046a', 
            name: 'Morningshade', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id,
        },
        { 
            id: 'ab9ad49e-da66-4b86-bc80-4f5f3c23ca74', 
            name: 'Korgarok', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.fury.id,
            role_id: charRoles.mdps.id, },
        { 
            id: '0fbc5ccf-fc4f-41e6-b1ee-fae2274c78c6', 
            name: 'Nyxalis',
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.shadow.id,
            role_id: charRoles.rdps.id,
        },
        {
            id: 'b6095d64-40b4-4d0b-adad-d1a56836aed9', 
            name: 'Aetherion', 
            class_id: charClasses.mage.id,
            spec_id: classTalentSpecs.mage.fire.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'b9a8cf83-cb1b-4ea6-b9d0-04ca4c59387b', 
            name: 'Drakkos', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.combat.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '9c92fc28-0851-4237-8544-52440791b607', 
            name: 'Felblade', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'c64b2201-ab5e-4539-ab8c-1d45a8568064', 
            name: 'Lyriax', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.unholy.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '3715d140-b44e-4cad-94b9-06dde12ef0b1', 
            name: 'Zenkaris', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.marksmanship.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'f4b9a2ae-f44c-4951-96a0-9a8e79ac64c3', 
            name: 'Ashenfury', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.fury.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '7f6782e7-0400-40ad-94ea-4a7f6fa01d75', 
            name: 'Vesperine', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.feralcat.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '6b7c989b-cb7a-4277-87b0-7a96c16773b8', 
            name: 'Kaltharion', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.balance.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '0ffa8c38-dfb5-4f54-8e63-0a5ce78c453c', 
            name: 'Miravelle', 
            class_id: charClasses.warlock.id,
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '6b77e472-cff3-4eb5-a900-69b10f013cfd', 
            name: 'Stormrune', 
            class_id: charClasses.shaman.id, 
            spec_id: classTalentSpecs.shaman.enhancement.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: 'b84428ef-a1b9-4d19-b156-e5cc49e0ae7d', 
            name: 'Thundrax', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.retribution.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '1e6af78e-d00e-40aa-a8a0-aa0f482820ad', 
            name: 'Nightwarden', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.retribution.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: 'a87aaf01-4557-4469-a4e2-01b9f76e0d22', 
            name: 'Frostbane', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.fire.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '184516f6-b85f-405d-9cdc-7c18d95369a3', 
            name: 'Lunarae', 
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.shadow.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '22c6fc11-6f17-438a-af48-eed0edf71777', 
            name: 'Grymshadow', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.affliction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '3a293121-574a-4562-bece-07728a808044', 
            name: 'Gorathar', 
            class_id: charClasses.shaman.id, 
            spec_id: classTalentSpecs.shaman.elemental.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '8a8a3d8a-a157-4f69-9ae2-154dbac30758', 
            name: 'Durok', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.arms.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '5e1b5bb7-b689-46a2-bcba-d54f2d23b9c5', 
            name: 'Morgath', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.assassination.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '3b306103-e925-422e-82b6-5ac6783187b0', 
            name: 'Varilynn', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.subtlety.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '7c80d8d5-a0c5-499f-9969-ea6cbb38dc85', 
            name: 'Sylthara', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.frost.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '284916b0-24ca-4493-8894-39b469c90959', 
            name: 'Lyriana', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.arcane.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'beb101e2-cd94-4ae4-b894-ec007414025d', 
            name: 'Kragor', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.frost.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '0979ee0c-ccff-4c5a-b6d5-30e420275e96', 
            name: 'Tharnak', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.affliction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: 'd8279bbf-8552-40ef-aea8-408dba9728c8', 
            name: 'Myralis', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.destruction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '86a23f3d-9c22-45b7-8557-adfee1b820c6', 
            name: 'Selindra', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.beastmastery.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '97d041b3-2398-4ce0-839b-cc33c64bf877', 
            name: 'Aerilynn', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.survival.id,
            role_id: charRoles.rdps.id, 
        },
    ],
    'example@gmail.com': [
        { 
            id: '73773822-3feb-4f84-8313-c2d08b176684', 
            name: 'Thaldrion', 
            class_id: charClasses.paladin.id,
            spec_id: classTalentSpecs.paladin.protection.id,
            role_id: charRoles.tank.id,},
        {
            id: 'f000af84-dc34-4c6c-bff5-eafbbe3c25be', 
            name: 'Zarathor', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.blood.id,
            role_id: charRoles.tank.id,  
        },
        {
            id: '3becd90a-8bde-4a8b-98a5-b3c0d3d7f9e3', 
            name: 'Baldur', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.protection.id,
            role_id: charRoles.tank.id, 
        },
        { 
            id: 'b6b5dcd8-7289-4041-94df-715ab4159428', 
            name: 'Elunara', 
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.discipline.id,
            role_id: charRoles.heal.id, 
        },
        { 
            id: '1982a222-a917-48eb-92cd-662bb3c664db', 
            name: 'Grommashar', 
            class_id: charClasses.shaman.id,
            spec_id: classTalentSpecs.shaman.restoration.id,
            role_id: charRoles.heal.id, 
        },
        { 
            id: '9bc65b32-26dd-4354-b5f7-8ce1c37a18fd', 
            name: 'Sylverwind', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.holy.id,
            role_id: charRoles.heal.id, 
        },
        {
            id: '2b409b2a-5172-4e3c-ad2d-c950486453c2', 
            name: 'Danathos', 
            class_id: charClasses.paladin.id,
            spec_id: classTalentSpecs.paladin.holy.id, 
            role_id: charRoles.heal.id, 
        },
        { 
            id: '7d7639cd-6c50-4a3d-a671-6a1551098722', 
            name: 'Vyraeth', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.restoration.id,
            role_id: charRoles.heal.id, 
        },
        {
            id: '41a56b98-d3ce-4818-97af-9727207760db', 
            name: 'Thalindra',
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.holy.id,
            role_id: charRoles.heal.id,
        },
        { 
            id: 'a115fce5-204f-4303-bd46-f3b5d25e2012', 
            name: 'Morningshade', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id,
        },
        { 
            id: '36fba807-e1ef-491f-bece-7f40ff8b2a28', 
            name: 'Korgarok', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.fury.id,
            role_id: charRoles.mdps.id, },
        { 
            id: 'f078e055-1132-443b-822b-e13b1c26c5cd', 
            name: 'Nyxalis',
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.shadow.id,
            role_id: charRoles.rdps.id,
        },
        {
            id: '26077910-b26b-492a-b799-743e7bcfe964', 
            name: 'Aetherion', 
            class_id: charClasses.mage.id,
            spec_id: classTalentSpecs.mage.fire.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '3d894266-2127-4034-a954-fe02f0bebf7d', 
            name: 'Drakkos', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.combat.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '401e236e-3544-417f-a866-5bb9b6a08bf2', 
            name: 'Felblade', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'ad88b8cc-3cd1-4954-b115-f5f32f87f53c', 
            name: 'Lyriax', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.unholy.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '17b6c270-b650-4794-a261-d58c35a0f63b', 
            name: 'Zenkaris', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.marksmanship.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'd446f206-38e4-4f4c-a828-6fd38f7c4da6', 
            name: 'Ashenfury', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.fury.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '214e7549-a031-4fd8-8ba3-109a8476bebb', 
            name: 'Vesperine', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.feralcat.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '3c30b832-1b45-493d-92ad-8bfadc2ce328', 
            name: 'Kaltharion', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.balance.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'a527a2bd-b2c1-4f88-b461-479d1914ecac', 
            name: 'Miravelle', 
            class_id: charClasses.warlock.id,
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '887e7b01-e9de-4787-937c-e474394cb08f', 
            name: 'Stormrune', 
            class_id: charClasses.shaman.id, 
            spec_id: classTalentSpecs.shaman.enhancement.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '1aba03f7-17fc-4c26-9d6f-29a208308310', 
            name: 'Thundrax', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.retribution.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '0b29db93-c702-4908-ba6a-76c4a0c9e900', 
            name: 'Nightwarden', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.retribution.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: 'feabbab9-4cb7-440d-ac12-86a0022d2b2c', 
            name: 'Frostbane', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.fire.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '03903d5b-7ea7-47b7-a96c-82fba9987b11', 
            name: 'Lunarae', 
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.shadow.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '07110c7a-0bc6-462d-bfc3-79360e0af998', 
            name: 'Grymshadow', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.affliction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '0e4227ca-7f11-416e-ac9e-f7f773ab2dbf', 
            name: 'Gorathar', 
            class_id: charClasses.shaman.id, 
            spec_id: classTalentSpecs.shaman.elemental.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '016568ea-e4e3-4659-8e5c-0b708bf6cf40', 
            name: 'Durok', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.arms.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '3ca955cf-0b89-4935-a040-4538e81b3f2c', 
            name: 'Morgath', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.assassination.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: 'f4ffd051-bf82-4d35-9122-ebd8664ef583', 
            name: 'Varilynn', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.subtlety.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '31d1a52c-0ca3-44ae-bf13-7304bf5fe03c', 
            name: 'Sylthara', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.frost.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '46ea894d-5348-44d4-9102-a8fb27d13530', 
            name: 'Lyriana', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.arcane.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '50ad7713-9e33-4434-b861-b54e1698e7a0', 
            name: 'Kragor', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.frost.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: 'cbceae65-6cd6-4384-9db3-d8aed08db5bb', 
            name: 'Tharnak', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.affliction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '347a819d-d0cc-4164-854d-268b2d2d33e7', 
            name: 'Myralis', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.destruction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '4a5381fe-ebda-4e16-9268-feb70bc68edf', 
            name: 'Selindra', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.beastmastery.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: 'f80c5acd-7979-4346-b5e1-4c5ae961efd6', 
            name: 'Aerilynn', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.survival.id,
            role_id: charRoles.rdps.id, 
        },
    ]
};

module.exports = {
    mainRosters
}