const { charClasses } = require('../../provisioning/data/charClasses.js')
const { charRoles } = require('../../provisioning/data/charRoles.js')
const { classTalentSpecs } = require('../../provisioning/data/classTalentSpecs.js')

const mainRosters = {
    'user@nextmail.com': [
        { 
            id: 'e76707d7-57c7-469c-933f-118a50eb17b8', 
            name: 'Thaldrion', 
            class_id: charClasses.paladin.id,
            spec_id: classTalentSpecs.paladin.protection.id,
            role_id: charRoles.tank.id,},
        {
            id: 'ccd1f7cb-d0de-4530-81fc-d48ff610658b', 
            name: 'Zarathor', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.blood.id,
            role_id: charRoles.tank.id,  
        },
        {
            id: '564bdf37-97ca-45b0-b733-97f1281ac8a9', 
            name: 'Baldur', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.protection.id,
            role_id: charRoles.tank.id, 
        },
        { 
            id: '282cfb5f-f20a-4f2b-8ad0-e89b965ef7ac', 
            name: 'Elunara', 
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.discipline.id,
            role_id: charRoles.heal.id, 
        },
        { 
            id: '53fbd70b-556a-452b-b704-38efbdb792b8', 
            name: 'Grommashar', 
            class_id: charClasses.shaman.id,
            spec_id: classTalentSpecs.shaman.restoration.id,
            role_id: charRoles.heal.id, 
        },
        { 
            id: 'acfc1c49-9a14-42f6-9e38-1599d060b98a', 
            name: 'Sylverwind', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.holy.id,
            role_id: charRoles.heal.id, 
        },
        {
            id: '8257599e-a08a-4af6-bf25-c9f6c40d6c64', 
            name: 'Danathos', 
            class_id: charClasses.paladin.id,
            spec_id: classTalentSpecs.paladin.holy.id, 
            role_id: charRoles.heal.id, 
        },
        { 
            id: 'e5065a59-3f49-4e44-97f4-fb519ce4f693', 
            name: 'Vyraeth', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.restoration.id,
            role_id: charRoles.heal.id, 
        },
        {
            id: '1645e24d-2ffe-456f-b038-9c6994fbcc0b', 
            name: 'Thalindra',
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.holy.id,
            role_id: charRoles.heal.id,
        },
        { 
            id: '6c6c031a-424a-43ae-a513-3bc36ff1046a', 
            name: 'Morningshade', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id,
        },
        { 
            id: 'ab9ad49e-da66-4b86-bc80-4f5f3c23ca74', 
            name: 'Korgarok', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.fury.id,
            role_id: charRoles.mdps.id, },
        { 
            id: '0fbc5ccf-fc4f-41e6-b1ee-fae2274c78c6', 
            name: 'Nyxalis',
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.shadow.id,
            role_id: charRoles.rdps.id,
        },
        {
            id: 'b6095d64-40b4-4d0b-adad-d1a56836aed9', 
            name: 'Aetherion', 
            class_id: charClasses.mage.id,
            spec_id: classTalentSpecs.mage.fire.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'b9a8cf83-cb1b-4ea6-b9d0-04ca4c59387b', 
            name: 'Drakkos', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.combat.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '9c92fc28-0851-4237-8544-52440791b607', 
            name: 'Felblade', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'c64b2201-ab5e-4539-ab8c-1d45a8568064', 
            name: 'Lyriax', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.unholy.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '3715d140-b44e-4cad-94b9-06dde12ef0b1', 
            name: 'Zenkaris', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.marksmanship.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'f4b9a2ae-f44c-4951-96a0-9a8e79ac64c3', 
            name: 'Ashenfury', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.fury.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '7f6782e7-0400-40ad-94ea-4a7f6fa01d75', 
            name: 'Vesperine', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.feralcat.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '6b7c989b-cb7a-4277-87b0-7a96c16773b8', 
            name: 'Kaltharion', 
            class_id: charClasses.druid.id, 
            spec_id: classTalentSpecs.druid.balance.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '0ffa8c38-dfb5-4f54-8e63-0a5ce78c453c', 
            name: 'Miravelle', 
            class_id: charClasses.warlock.id,
            spec_id: classTalentSpecs.warlock.demonology.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '6b77e472-cff3-4eb5-a900-69b10f013cfd', 
            name: 'Stormrune', 
            class_id: charClasses.shaman.id, 
            spec_id: classTalentSpecs.shaman.enhancement.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: 'b84428ef-a1b9-4d19-b156-e5cc49e0ae7d', 
            name: 'Thundrax', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.retribution.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: '1e6af78e-d00e-40aa-a8a0-aa0f482820ad', 
            name: 'Nightwarden', 
            class_id: charClasses.paladin.id, 
            spec_id: classTalentSpecs.paladin.retribution.id,
            role_id: charRoles.mdps.id, 
        },
        { 
            id: 'a87aaf01-4557-4469-a4e2-01b9f76e0d22', 
            name: 'Frostbane', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.fire.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '184516f6-b85f-405d-9cdc-7c18d95369a3', 
            name: 'Lunarae', 
            class_id: charClasses.priest.id, 
            spec_id: classTalentSpecs.priest.shadow.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: '22c6fc11-6f17-438a-af48-eed0edf71777', 
            name: 'Grymshadow', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.affliction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '3a293121-574a-4562-bece-07728a808044', 
            name: 'Gorathar', 
            class_id: charClasses.shaman.id, 
            spec_id: classTalentSpecs.shaman.elemental.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '8a8a3d8a-a157-4f69-9ae2-154dbac30758', 
            name: 'Durok', 
            class_id: charClasses.warrior.id, 
            spec_id: classTalentSpecs.warrior.arms.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '5e1b5bb7-b689-46a2-bcba-d54f2d23b9c5', 
            name: 'Morgath', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.assassination.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '3b306103-e925-422e-82b6-5ac6783187b0', 
            name: 'Varilynn', 
            class_id: charClasses.rogue.id, 
            spec_id: classTalentSpecs.rogue.subtlety.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '7c80d8d5-a0c5-499f-9969-ea6cbb38dc85', 
            name: 'Sylthara', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.frost.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '284916b0-24ca-4493-8894-39b469c90959', 
            name: 'Lyriana', 
            class_id: charClasses.mage.id, 
            spec_id: classTalentSpecs.mage.arcane.id,
            role_id: charRoles.rdps.id, 
        },
        { 
            id: 'beb101e2-cd94-4ae4-b894-ec007414025d', 
            name: 'Kragor', 
            class_id: charClasses.deathknight.id, 
            spec_id: classTalentSpecs.deathknight.frost.id,
            role_id: charRoles.mdps.id, 
        },
        {
            id: '0979ee0c-ccff-4c5a-b6d5-30e420275e96', 
            name: 'Tharnak', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.affliction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: 'd8279bbf-8552-40ef-aea8-408dba9728c8', 
            name: 'Myralis', 
            class_id: charClasses.warlock.id, 
            spec_id: classTalentSpecs.warlock.destruction.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '86a23f3d-9c22-45b7-8557-adfee1b820c6', 
            name: 'Selindra', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.beastmastery.id,
            role_id: charRoles.rdps.id, 
        },
        {
            id: '97d041b3-2398-4ce0-839b-cc33c64bf877', 
            name: 'Aerilynn', 
            class_id: charClasses.hunter.id, 
            spec_id: classTalentSpecs.hunter.survival.id,
            role_id: charRoles.rdps.id, 
        },
    ]
};

module.exports = {
    mainRosters
}